name: Subscribers
description: Minecarts.com subscriber manager
author: megabytes
website: http://minecarts.com/

main: com.minecarts.subscribers.Subscribers
version: ${pom.version}
depend: [ DBPermissions ]
