name: Subscribers
description: Minecarts.com subscriber manager
author: megabytes
website: http://minecarts.com/

main: com.minecarts.subscribers.Subscribers
version: ${pom.version}
softdepend: [ DBPermissions ]

commands:
    subscribers:
        aliases: [ sub, subscriber ]
        description: Subscribers internal plugin commands
        usage: /<command> reload
        
permissions:
    subscribers:
        admin.reload:
            description: Reload Subscribers config
            default: op

